### ISSUE TITLE
后端如何启动，如何mock数据

### ISSUE THREAD

**Issue by IMLaoJI** [RootLinkFE/roothub#3]

**Comment by giscafer** [comment]
`recommendMaterials.json` 改 ant-design 仓库的地址和 `active` 为true，把我这边个人的 `materials-vue` 关掉， `active` 设置为 false。

- yarn
- yarn dev
- 正常打开页面就会自动同步物料，如果失败，手动点击同步物料。

**Comment by IMLaoJI** [comment]
按照上述操作，打开页面，物料源下拉框还是为空的，手动点击同步物料也不行，需要启动server吗

**Comment by IMLaoJI** [comment]
已解决 感谢作者
