### ISSUE TITLE
rh block 使用体验改进

### ISSUE THREAD

**Issue by zomixi** [RootLinkFE/roothub#5]
### 现象
rh block 拉取物料仓库时，若用户本地存在老仓库（仓库地址已改变），会导致拉取失败。

### 解决思路
1. 拉取失败后，获取本地仓库地址，再对比仓库地址，如果不一致给出提示`仓库地址已改变`
2. 提供一个命令 `rh material clean`清除`.roothub`的目录，提示用户先执行命令清除缓存后再执行`rh block`

**Comment by giscafer** [comment]
done
